import streamlit as st
import pandas as pd
import numpy as np
from scipy.stats import norm
from fpdf import FPDF
import datetime

# 設定頁面
st.set_page_config(page_title="Tolerance Stack-up Tool", layout="wide")

# --- CSS 樣式：調整結果數值與標題字體 ---
st.markdown("""
    <style>
    /* 數值放大至 30px 且加粗 */
    [data-testid="stMetricValue"] {
        font-size: 30px !important;
        font-weight: bold !important;
        color: #1f77b4 !important;
    }
    /* 標題文字放大 1.5 倍 (約 24px) */
    [data-testid="stMetricLabel"] {
        font-size: 24px !important;
        font-weight: bold !important;
    }
    /* 縮小元件間距 */
    .element-container { margin-bottom: -10px !important; }
    .stImage { margin-bottom: -20px !important; }
    h3 { margin-top: -10px !important; padding-bottom: 10px !important; }
    </style>
    """, unsafe_allow_html=True)

# --- PDF 產生函數 (彙整至 A4) ---
def create_pdf(proj, title, date, unit, target, wc, rss, yield_val, cpk, df):
    pdf = FPDF(orientation='P', unit='mm', format='A4')
    pdf.add_page()
    
    # 設定字體 (PDF 僅支援英文字元)
    pdf.set_font("Arial", 'B', 18)
    pdf.cell(190, 15, txt="Tolerance Analysis Report", ln=True, align='C')
    pdf.ln(5)

    # 專案基本資訊區
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(95, 10, txt=f"Project: {proj}", border=1)
    pdf.cell(95, 10, txt=f"Title: {title}", border=1, ln=True)
    pdf.cell(95, 10, txt=f"Date: {date}", border=1)
    pdf.cell(95, 10, txt=f"Unit: {unit}", border=1, ln=True)
    pdf.ln(10)

    # 分析結果 (重點區域)
    pdf.set_font("Arial", 'B', 14)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(190, 10, txt="Analysis Results", ln=True, fill=True)
    pdf.set_font("Arial", '', 12)
    pdf.cell(63, 10, txt=f"Worst Case: +/- {wc:.3f}", border=1)
    pdf.cell(63, 10, txt=f"RSS Total: +/- {rss:.3f}", border=1)
    pdf.cell(64, 10, txt=f"Target: +/- {target:.3f}", border=1, ln=True)
    pdf.cell(95, 10, txt=f"Est. Yield: {yield_val:.2f} %", border=1)
    pdf.cell(95, 10, txt=f"Est. CPK: {cpk:.2f}", border=1, ln=True)
    pdf.ln(10)

    # 數據明細
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(190, 10, txt="Input Data Table Detail", ln=True)
    pdf.set_font("Arial", size=10)
    # 表格標題
    pdf.cell(30, 8, "Part", 1)
    pdf.cell(20, 8, "No.", 1)
    pdf.cell(100, 8, "Description", 1)
    pdf.cell(40, 8, "Tol (+/-)", 1, ln=True)
    # 表格內容
    for index, row in df.iterrows():
        pdf.cell(30, 8, str(row['Part']), 1)
        pdf.cell(20, 8, str(row['No.']), 1)
        pdf.cell(100, 8, str(row['Description']), 1)
        pdf.cell(40, 8, f"{row['Upper Tol']:.3f}", 1, ln=True)

    pdf.ln(10)
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(190, 10, txt=f"Generated by Tolerance Stack-up Tool - {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}", align='R')
    
    return pdf.output(dest="S").encode("latin-1")

# --- 資料初始化 ---
DEFAULT_DATA = [
    {"Part": "PCB", "Req. CPK": 1.33, "No.": "a", "Description": "Panel mark to unit mark", "Upper Tol": 0.100, "Lower Tol": 0.100},
    {"Part": "PCB", "Req. CPK": 1.33, "No.": "b", "Description": "Unit mark to soldering pad", "Upper Tol": 0.100, "Lower Tol": 0.100},
    {"Part": "SMT", "Req. CPK": 1.00, "No.": "c", "Description": "SMT tolerance", "Upper Tol": 0.150, "Lower Tol": 0.150},
    {"Part": "Connector", "Req. CPK": 1.33, "No.": "d", "Description": "Connector housing (0.25/2)", "Upper Tol": 0.125, "Lower Tol": 0.125},
]

if 'df_data' not in st.session_state:
    st.session_state.df_data = pd.DataFrame(DEFAULT_DATA)

def clear_all():
    st.session_state.df_data = pd.DataFrame(columns=["Part", "Req. CPK", "No.", "Description", "Upper Tol", "Lower Tol"])

def reset_default():
    st.session_state.df_data = pd.DataFrame(DEFAULT_DATA)

# --- 介面 ---
st.markdown("<h2 style='text-align: center;'>設計累計公差分析</h2>", unsafe_allow_html=True)
st.markdown("<h4 style='text-align: center;'>Design Tolerance Stack-up Analysis</h4>", unsafe_allow_html=True)

with st.container():
    c1, c2 = st.columns(2)
    with c1:
        proj_name = st.text_input("專案名稱 (Project Name)", "TM-P4125-001")
        title_text = st.text_input("分析標題 (Title)", "Connector Y-Position Analysis")
    with c2:
        date_text = st.text_input("日期 (Date)", "2025/12/29")
        unit_text = st.text_input("尺寸單位 (Unit)", "mm")

st.divider()

# --- 範例圖片 ---
st.subheader("範例示意圖 (Example Diagram)")
try:
    st.image("4125.jpg", caption="公差標註範例", use_container_width=True)
except:
    st.info("💡 提示：若要自動顯示範例圖，請確保 GitHub 內有 4125.jpg")
    uploaded_image = st.file_uploader("或手動匯入圖片檔", type=["png", "jpg", "jpeg"], key="uploader")
    if uploaded_image:
        st.image(uploaded_image, use_container_width=True)

st.divider()

# --- 數據輸入 ---
st.subheader("公差數據輸入 (Input Table)")
col_btn1, col_btn2, _ = st.columns([1, 1, 4])
with col_btn1:
    st.button("🗑️ 一鍵清除", on_click=clear_all, use_container_width=True)
with col_btn2:
    st.button("🔄 一鍵還原範例", on_click=reset_default, use_container_width=True)

edited_df = st.data_editor(st.session_state.df_data, num_rows="dynamic", use_container_width=True)
st.session_state.df_data = edited_df

target_spec = st.number_input("目前設計公差目標 (Target Spec ±)", value=0.200, format="%.3f")

# --- 核心邏輯計算 ---
if not edited_df.empty and "Upper Tol" in edited_df.columns:
    wc = edited_df["Upper Tol"].sum()
    rss = np.sqrt((edited_df["Upper Tol"]**2).sum())
    cpk = target_spec / rss if rss != 0 else 0
    yield_val = (2 * norm.cdf(3 * cpk) - 1) * 100
else:
    wc, rss, cpk, yield_val = 0, 0, 0, 0

st.divider()

# --- 結果顯示 (標題放大 1.5 倍，數字 30px) ---
st.subheader("分析結果 (Results)")
r1, r2, r3 = st.columns(3)
r1.metric("Worst Case", f"± {wc:.3f} mm")
r2.metric("RSS Total", f"± {rss:.3f} mm")
r3.metric("預估良率 (Yield)", f"{yield_val:.2f} %")

st.info(f"結論：若採用 {target_spec:.3f} mm 為規格，預估良率為 {yield_val:.2f}%，CPK 為 {cpk:.2f}。")

# PDF 匯出按鈕 (彙整 A4)
try:
    pdf_bytes = create_pdf(proj_name, title_text, date_text, unit_text, target_spec, wc, rss, yield_val, cpk, edited_df)
    st.download_button("📥 匯出 A4 PDF 報告", data=pdf_bytes, file_name=f"Report_{proj_name}.pdf", mime="application/pdf")
except Exception as e:
    st.warning("PDF 目前僅支援英文內容顯示。")
